[commands.swipe.three]
left_up = ""
right_up = ""
up = ""
left_down = ""
right_down = ""
down = "fuzzel"
left = "swaymsg -t command workspace next"
right = "swaymsg -t command workspace prev"

[commands.swipe.four]
left_up = ""
right_up = ""
up = ""
left_down = ""
right_down = ""
down = ""
left = ""
right = ""
